name: dart_tools
description: A sample command-line application.
version: 0.0.1-alpha.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  meta: ^1.17.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
