name: dart_tools
description: Biblioteca de códigos para Dart.
version: 0.0.1-alpha.1
repository: https://github.com/guilherme-paiva2007/dart_tools

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
